name: Run Synopsys-Action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LINUX_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/0.1.244/synopsys-bridge-0.1.244-linux64.zip"
      #MAC_BRIDGE_URL: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/0.1.225/synopsys-bridge-0.1.225-mac64.zip"
      ##WINDOWS_BRIDGE_URL: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/synopsys-bridge/0.1.225/synopsys-bridge-0.1.225-win64.zip"
    steps:
      - uses: actions/checkout@v2
      - name: Use synopsys-action
        uses: synopsys-sig/synopsys-action@main
        with:
          include_diagnostics: true
          
          #polaris_serverUrl: ${{secrets.POLARIS_URL}}
          #polaris_accessToken: ${{secrets.POLARIS_TOKEN}}
          #polaris_application_name: "fAST Dynamic Projects"
          #polaris_project_name: "fAST DAST Engine"
          #polaris_assessment_types: "SCA,SAST"

          #blackduck_url: ${{ secrets.BD_URL}}
          #blackduck_apiToken: ${{ secrets.BD_TOKEN}}
          #blackduck_scan_full: true
          #blackduck_scan_failure_severities: "ALL"
          #github_token: ${{ secrets.GH_TOKEN}}
          #blackduck_automation_fixpr: true
          #blackduck_automation_prcomment: true
          
          coverity_url: ${{secrets.cov_url}}
          coverity_user: ${{secrets.cov_user}}
          #coverity_passphrase: ${{secrets.cov_pass}}
          coverity_project_name: 'tb test'
          coverity_stream_name: 'tb nodegoat'
          

