
name: CI-Polaris
on:
  push:
    branches: [ master, main ]
  workflow_dispatch:  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Polaris Scan
        uses: synopsys-sig/synopsys-action@v1.2.0
        with:
          polaris_serverUrl: ${{ secrets.POLARIS_SERVERURL }}
          polaris_accessToken: ${{ secrets.POLARIS_ACCESSTOKEN }}
          polaris_application_name: ${{ github.event.repository.name }}
          polaris_project_name: ${{ github.event.repository.name }}

          polaris_assessment_types: "SAST,SCA"
          include_diagnostics: true
